test

diff --git a/.github/workflows/cmake.yml b/.github/workflows/cmake.yml
--- a/.github/workflows/cmake.yml
+++ b/.github/workflows/cmake.yml
@@ -51,6 +51,9 @@ jobs:
     - name: Test2
       run: ls ${{ github.workspace }}
 
+    - name: Verify CMakePresets.json
+      run: test -f ${{ github.workspace }}/CMakePresets.json || echo "CMakePresets.json is missing!"
+
     - name: Configure CMake
       run: cmake --preset Release
 
